import type { Metadata } from "next";
import "@highschool/ui/globals.css";
import { AppProviders } from "@/components/core/providers/app-provider";
import { auth } from "@highschool/react-query/auth";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth();
    return (
        <html lang="vi" suppressHydrationWarning>
            <body className={` antialiased w-screen `}>
                <AppProviders session={session!}>{children}</AppProviders>
            </body>
        </html>
    );
}
