import type { Metadata } from "next";

import { Suspense } from "react";

import "@highschool/ui/globals.css";
import { cn } from "@highschool/ui/lib/utils";
import { auth } from "@highschool/react-query/auth";

import { Loading } from "@/components/core/common/loading";
import { sofiaFontVN } from "@/lib/fonts";
import { AppProviders } from "@/components/core/providers/app-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html suppressHydrationWarning lang="vi">
      <body
        className={cn(
          "w-screen bg-gray-50 font-sans dark:bg-gray-900/50",
          sofiaFontVN.variable,
        )}
      >
        <Suspense fallback={<Loading />}>
          <AppProviders session={session ?? undefined}>{children}</AppProviders>
        </Suspense>
      </body>
    </html>
  );
}
