import { Metadata } from "next";

import { Inter } from "next/font/google";

import { auth } from "@highschool/react-query/auth";
import "@highschool/ui/globals.css";
import { cn } from "@highschool/ui/lib/utils";

import AppProviders from "@/components/core/commons/provider/app-provider";
import { sofiaFontVN } from "@/lib/fonts";

import "./global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="vi">
      <body
        className={cn("bg-[#F0F4FF] font-sans", sofiaFontVN.variable)}
        suppressHydrationWarning
      >
        <AppProviders session={session ?? undefined}>{children}</AppProviders>
      </body>
    </html>
  );
}
