"use client";

import "@highschool/ui/globals.css";

import AppProviders from "@/components/core/common/provider/app-provider";
import AblyWrapper from "@/utils/ably-provider";

import "./global.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppProviders>
          <AblyWrapper>{children}</AblyWrapper>
        </AppProviders>
      </body>
    </html>
  );
}
